
credentials:
  usernames:
    admin:
      email: admin@safaricom.com
      name: Admin User
      password: '123'
    evaluator:
      email: eval@safaricom.com
      name: Evaluator User
      password: '456'

cookie:
  expiry_days: 30
  key: 'some_signature_key'
  name: 'esp_onboarding_auth'
