
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_NAME=esp_onboarding
      - DB_USER=esp_user
      - DB_PASS=esp_pass
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: esp_onboarding
      POSTGRES_USER: esp_user
      POSTGRES_PASSWORD: esp_pass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
